### ISSUE TITLE
Mobile score is 70 instead of 90+

### ISSUE THREAD

**Issue by nsursock** [eddiesigner/liebling#205]
Hello,

Congrats for your awesome ghost theme. But I have one question.

I need a fast theme and casper scores 90+ on mobile. Your theme scores 70 on mobile (even though I used to be around 85, I don't know why it went down).
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fsoundsirius.digitalpress.blog%2F&tab=desktop

Please help me make your theme score 90+ on mobile on my website.
https://soundsirius.digitalpress.blog/

**Comment by kittu999c** [comment]
I'm facing the same issue after shifting from Casper. Please help.

**Comment by eddiesigner** [comment]
@kittu999c It's hard to help you if you don't provide an url, every website has different issues and the solutions might vary from a website to another.

**Comment by eddiesigner** [comment]
@nsursock At the moment your website scores 81 on mobile which is still not good. The thing is, PageSpeed Insights change the parameters from time to time, a lot of things changed since Google released [Web Vitals](https://web.dev/vitals/), that's why the score changed in the first place.

I can address some issues definitely but it would take some time since currently I'm quite busy with other stuff, hope I can work on this next week or so.

For now you can do a couple of things as well to improve your score, for example:

1. [Enable the search](https://github.com/eddiesigner/liebling/wiki/How-to-enable-search) so the related code is not unused.

2. Consider if you want to keep Google Analytics and Momently since both also affect the score, or maybe looking for some better way to include them in your website.

3. Compress and save [this picture](https://digitalpress.fra1.cdn.digitaloceanspaces.com/9ebx8sq/2020/05/monica-silva-2o3HrdMUkJg-unsplash.jpg) as JPEG or WebP.

4. [Serve static assets with an efficient cache policy](https://web.dev/uses-long-cache-ttl). The theme is not responsible for this, you have to configure that on your server. If you're not sure about how to solve this, you can ask for help with your hosting provider.

**Comment by nsursock** [comment]
2. I already did a trick for hotjar tracking that only loads on mobile. What do you mean a better way to include them?
3. Done
1. Done
4. My hosting provider says everything's fine on their side.

I need a website that loads under 1 second and I need to make sure your theme is top notch. Casper still scores 90+ even if I include tracking.

**Comment by nsursock** [comment]
I think something important to do is to use srcset for images. I don't know if you use that techniques to properly size images depending on screen size. But casper clearly makes use of it and makes the blog fast.

**Comment by nsursock** [comment]
Also the subscribe page isn't working. It's working fine in posts but the button on the homepage gives a 404.

**Comment by eddiesigner** [comment]
I will address some of those issues as soon as I have time for it, but the subscribe page works, you just need to follow the steps described here: https://github.com/eddiesigner/liebling/wiki/How-to-enable-subscribers

You actually need to create the a page for the newsletter in the Admin, not only adding the link to it.

**Comment by nsursock** [comment]
I did the following tests with pingdom so you can get inspired. Casper is 88 (google) on mobile and I need the beauty of your theme with the speed of Casper. It makes a big difference on 3G.
https://pasteboard.co/JdxaMag.png (casper)
https://pasteboard.co/Jdxb5TK.png (liebling)

**Comment by nsursock** [comment]
If you can make liebling load in less than 1 second, it will be an awesome feat. Plus can you consider including tailwind css by default? I see you already use lozad.

**Comment by eddiesigner** [comment]
I won't include Tailwindcss since you can include it by your own if you need it, since this theme don't use it, it's not a good idea to include it. Also, you can't expect having faster loading times if you'are adding frameworks like that, if you decide to include them, you have to solve possible issues with them by your own.

**Comment by nsursock** [comment]
Hello I have news: the website loses a lot of time twice while doing nothing.
https://yellowlab.tools/result/forqc5lwvr/timeline

from 1.6sec until 2.9sec: there's no activity. that's more than 1 second wasted
again from 3sec until 3.5sec: there's no activity.

I have included a screenshot. Is your theme at responsible for this?
<img width="1440" alt="wasted-time" src="https://user-images.githubusercontent.com/1311831/85928539-5e11b980-b8b6-11ea-918a-c7e664991f7b.png">

**Comment by nsursock** [comment]
I got some feedback from ghost forums: https://forum.ghost.org/t/my-blog-does-nothing-during-2-2-seconds-mobile/15441/2
 - Fix Style Recalculation: There is quite a bit of style recalculation going on your site, probably due to your css and the vendor.js which seems to shift your site around while loading.
 - Vendor.js loads your images, but you deferred it via the in your defer attribute in your script. It's basically waiting waiting waiting until the html is parsed and then starts to insert images and stuff. Is that intentional?

**Comment by eddiesigner** [comment]
[Version 0.7.3](https://github.com/eddiesigner/liebling/releases/tag/v.0.7.3) is out and it solves multiple javascript-related issues, I encourage you to download this new version and test it again.

![CleanShot 2020-06-29 at 16 13 31](https://user-images.githubusercontent.com/1477503/86016784-85d26000-ba23-11ea-90eb-89c781b58a16.png)

![CleanShot 2020-06-29 at 16 14 21](https://user-images.githubusercontent.com/1477503/86016858-9d114d80-ba23-11ea-806d-9553d481f74c.png)

As you can see now, in PageSpeed Insights it scores 94 on desktop and 87 on mobile. Be aware that the score is almost never the same, it can change from one test to another but in general the score is better now.

![CleanShot 2020-06-29 at 16 17 08](https://user-images.githubusercontent.com/1477503/86017166-01341180-ba24-11ea-81c8-9c9c7c68a0bb.png)

Also, the score is way better now in the Yellow Lab Tools.

Although, there are still some issues that I can't solve by myself because those issues are not created by this theme but by Ghost itself and some third-party libraries.

Also there are some improvements that I have to implement in the CSS but that will take some days because I have to reorganize the stylesheets and make a lot of changes, after that the score should be even better but you can't expect having scores really close to 100% because that depends on several things, not only on this theme.

Finally, you should've mentioned that you modified this theme and added libraries by yourself, a lot of issues exist in your reports because of that, so please I encourage you to test your website with the new version of this theme **without customizations**. As I said before, if you add code or libraries by yourself, you're responsible for the issues that might appear because of them.

**Comment by nsursock** [comment]
Hello,

Long story short: the killer optimisation would be to load the right image based on screen size AND container size. Ghost said that normally the CMS optimises images automatically. The hero picture is also affecting the score on google.

More details:
Sadly, it didn't make a big difference on google pagespeed (mobile). I think there's something important to do on mobile with images. In ghost, i'm uploading images max 100kb. I have uploaded on Netlify 2 versions: desktop (100kb) and mobile (max 25kb). Now you should use srcsets like Casper I guess even though it needs configuration and my plan on digitalpress doesn't allow me to do it.

But i was thinking that the real killer feature would be to load the right image based on the div element width. For example, the landing page on desktop needs the mobile version for article cards. The featured slider though could use big images.

Pingdom says:
Image | 71.83% | 953.9 KB
Script | 12.76% | 169.5 KB
CSS | 8.52% | 113.1 KB
Font | 4.52% | 60.0 KB

Casper is still at 86 mobile and Liebling is at 73. Desktop is fine. But to be honest, Casper shows some bugs sometimes when I use Tailwind CSS components from other websites.

**Comment by adityapatadia** [comment]
Hi, tools like Gumlet (https://www.gumlet.com) can optimise images very well but it works better if background images are not used. Currently I can see the story page main image is set as background. Is there any way to change that?

**Comment by nsursock** [comment]
Thanks for the info adityapatadia. One last thing: it seems the featured slider needs improvement (page almost complete at 1.4s and then until 3.2s featured slider is working).
<img width="1440" alt="featured-speed" src="https://user-images.githubusercontent.com/1311831/86622748-17fcda00-bfc9-11ea-9ea6-d1345599065e.png">

**Comment by eddiesigner** [comment]
After making some changes I managed to improve the score significantly, now it gets an score of 93 on mobile and 98 on desktop as you can see in the screenshots bellow:

![CleanShot 2020-07-08 at 00 00 18](https://user-images.githubusercontent.com/1477503/86953224-6d192700-c154-11ea-81cd-0f40e0d71fd9.png)
![CleanShot 2020-07-08 at 00 00 43](https://user-images.githubusercontent.com/1477503/86953251-75716200-c154-11ea-87db-d1197e867f58.png)

I also fixed the issue with the featured articles as you can see here:

![CleanShot 2020-07-08 at 19 59 33](https://user-images.githubusercontent.com/1477503/86954000-925a6500-c155-11ea-960b-730e44a2f0c6.png)

Although there was a problem, that didn't mean that the site took 3.2 seconds to start working, that time was used to build slides that worked as clones to run the carousel in infinite mode. I decided to remove that functionality.

Please download the latest version to get all these improvements: https://github.com/eddiesigner/liebling/releases/tag/v.0.7.6

@nsursock Please note that your website still has lots of customizations, for example, you're loading some tracking libraries, you're loading Tailwindcss and you also have some weird javascript code that seems unnecessary, all those things affect and will prevent your website from getting a good score. As I said in a previous comment, please test your website with this new version of the theme **WITHOUT CUSTOMIZATIONS**, please don't report anything else if you don't do it in that way, I'm not responsible of solving issues that are triggered by your own changes.

I recommend you both to not use Unsplash directly in the Ghost admin when editing a post because Ghost doesn't generate small versions of those images, it only does it when you upload images through the input file:

![CleanShot 2020-07-08 at 20 07 27](https://user-images.githubusercontent.com/1477503/86954663-b1a5c200-c156-11ea-8906-83e0d418f9e8.png)

**Comment by nsursock** [comment]
Your theme now loads very fast. Great job. But I still get largest Contentful paint problems on Google PageSpeed. it depends what it identifies as LCP. when the hero picture is selected I'm in the red. otherwise it selects the featured bg image and says speed is 85+. yellow lab says everything's fine though and I'm loading in less than 1 second. https://yellowlab.tools/result/fp8dvbepgw/timeline
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fsoundsirius.digitalpress.blog

**Comment by eddiesigner** [comment]
Your blog still has customizations made by yourself, a quick look on your site I can identify some potential problems that might lead to a lower score:

![CleanShot 2020-07-13 at 10 36 04](https://user-images.githubusercontent.com/1477503/87282545-ace56300-c4f4-11ea-8543-839a32ce4709.png)

This is not a customization but for some reason you're uploading the image from some CDN or i don't know from where but it wasn't done in the Ghost admin using the input file, that's why Ghost didn't generate smaller versions.

![CleanShot 2020-07-13 at 10 38 44](https://user-images.githubusercontent.com/1477503/87282917-0c437300-c4f5-11ea-8ee4-b05ae2fec77c.png)

In the screenshot above I can see that you're running some weird javascript code that manipulates the hero element, I don't know why do you need it but also affects.

![CleanShot 2020-07-13 at 10 40 51](https://user-images.githubusercontent.com/1477503/87283295-722ffa80-c4f5-11ea-9b91-67f809a83444.png)

Also, you're loading a different font after the one used by the theme was already downloaded and then you apply some styles to several elements (including the hero title).

And lastly, you're loading Tailwindcss for some reason.

As I already said multiple times, you must test your website with the latest version of this theme and without customizations, sorry but I don't have time to solve issues that are not related to the theme itself, you can use Stackoverflow for that.

I will close this issue as there are no significant improvements I can make for now.
